apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile-pod
  template:
    metadata:
      labels:
        app: userprofile-pod
    spec:
      containers:
      - name: userprofile-pod
        image: registryygo2491.azurecr.io/userprofile:latest
        ports:
        - containerPort: 8061
        env: 
        - name: SQL_USER
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_password
        - name: SQL_SERVER
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_server         
        - name: SQL_DBNAME
          value: "mydrivingDB"    
        - name: PORT
          value: "8061"    
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-svc
spec:
  selector:
    app: userprofile-pod
  ports:
    - protocol: TCP
      port: 8102
      targetPort: 8061
# ---      
# apiVersion: v1
# kind: Service
# metadata:
#   name: userprofile-public-svc
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8062
#       targetPort: 8061
#   selector:
#     app: userprofile-pod  