apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java-pod
  template:
    metadata:
      labels:
        app: user-java-pod
    spec:
      containers:
      - name: user-java-pod
        image: registryygo2491.azurecr.io/user-java:latest
        ports:
        - containerPort: 8071
        env: 
        - name: SQL_USER
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_password
        - name: SQL_SERVER
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_server          
        - name: SQL_DBNAME
          value: "mydrivingDB"    
        - name: PORT
          value: "8071"    
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-svc
spec:
  selector:
    app: user-java-pod
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8071              
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-public-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8072
      targetPort: 8071
  selector:
    app: user-java-pod          
