# This is a SecretProviderClass example using user-assigned identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi-v2
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "77264a2e-19a4-4026-be19-dc20765db7f0"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "team4-kv"        # Set to the name of your Azure Key Vault instance
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    tenantId: "56a831ed-4f17-4a42-8c08-ad7a78591f7f"                 # The tenant ID of the Azure Key Vault instance
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: dbpassword                           # data field to populate
      objectName: dbpassword                        # name of the mounted content to sync. this could be the object name or the object alias
    - key: dbserver                           # data field to populate
      objectName: dbserver
    - key: dbuser                           # data field to populate
      objectName: dbuser
    secretName: oursecret                     # name of the Kubernetes Secret object
    type: Opaque  
    