apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  labels:
    app: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips-pod
  template:
    metadata:
      labels:
        app: trips-pod
    spec:
      containers:
      - name: trips-pod
        image: registryygo2491.azurecr.io/trips:latest
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true 
        ports:
        - containerPort: 8080
        env:       
        - name: SQL_DBNAME
          value: "mydrivingDB"    
        - name: PORT
          value: "8080"    
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0" 
        - name: CONFIG_FILES_PATH
          value: "/secrets" 
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"           
        - name: OPENAPI_DOCS_URI
          value: "http://changeme"
        - name: DEBUG_LOGGING
          value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: trips-svc
  namespace: api
spec:
  selector:
    app: trips-pod
  ports:
    - protocol: TCP
      port: 8104
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trips-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /api/trips/*
        backend:
          service:
            name: trips-svc
            port:
              number: 8104
        pathType: Prefix              