apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java-pod
  template:
    metadata:
      labels:
        app: user-java-pod
    spec:
      containers:
      - name: user-java-pod
        image: registryygo2491.azurecr.io/user-java:latest
        ports:
        - containerPort: 8080
        env: 
        - name: SQL_USER
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_password
        - name: SQL_SERVER
          valueFrom: 
            secretKeyRef:
              name: db-secret
              key: db_server          
        - name: SQL_DBNAME
          value: "mydrivingDB"    
        - name: PORT
          value: "8080"    
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-svc
  namespace: api
spec:
  selector:
    app: user-java-pod
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8080            
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-java-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /api/user-java/*
        backend:
          service:
            name: user-java-svc
            port:
              number: 8100
        pathType: Prefix  