apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-java-pod
  template:
    metadata:
      labels:
        app: user-java-pod
    spec:
      containers:
      - name: user-java-pod
        image: registryygo2491.azurecr.io/user-java:latest
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true 
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /api/user-java/healthcheck
            port: 8080
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /api/user-java/healthcheck
            port: 8080      
          timeoutSeconds: 30     
        env:           
        - name: SQL_DBNAME
          value: "mydrivingDB"    
        - name: PORT
          value: "8080"    
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-svc
  namespace: api
spec:
  selector:
    app: user-java-pod
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8080            
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-java-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /api/user-java/*
        backend:
          service:
            name: user-java-svc
            port:
              number: 8100
        pathType: Prefix  