kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev
subjects:
- kind: Group
  namespace: api
  name: efc9776b-d7d8-47c7-b4ca-c4d7981b625a
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev
subjects:
- kind: Group
  namespace: web
  name: bfc6fb38-d4d1-49f9-8e3f-3af7783e6215